# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from criteria.v2 import adapter_pb2 as criteria_dot_v2_dot_adapter__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in criteria/v2/adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterServiceStub(object):
    """AdapterService is the out-of-process adapter contract for Criteria v2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/criteria.v2.AdapterService/Info',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.InfoRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/criteria.v2.AdapterService/OpenSession',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/criteria.v2.AdapterService/Execute',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.Log = channel.unary_stream(
                '/criteria.v2.AdapterService/Log',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.LogRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.LogEvent.FromString,
                _registered_method=True)
        self.Permissions = channel.stream_stream(
                '/criteria.v2.AdapterService/Permissions',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.PermissionEvent.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.PermissionDecision.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/criteria.v2.AdapterService/Pause',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.PauseRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/criteria.v2.AdapterService/Resume',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.ResumeRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/criteria.v2.AdapterService/Snapshot',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/criteria.v2.AdapterService/Restore',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.RestoreRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.RestoreResponse.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/criteria.v2.AdapterService/Inspect',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.InspectRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/criteria.v2.AdapterService/CloseSession',
                request_serializer=criteria_dot_v2_dot_adapter__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=criteria_dot_v2_dot_adapter__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class AdapterServiceServicer(object):
    """AdapterService is the out-of-process adapter contract for Criteria v2.
    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Permissions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.InfoRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.InfoResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.OpenSessionRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.OpenSessionResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.ExecuteRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.ExecuteEvent.SerializeToString,
            ),
            'Log': grpc.unary_stream_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.LogRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.LogEvent.SerializeToString,
            ),
            'Permissions': grpc.stream_stream_rpc_method_handler(
                    servicer.Permissions,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.PermissionEvent.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.PermissionDecision.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.PauseRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.PauseResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.ResumeRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.ResumeResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.SnapshotRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.SnapshotResponse.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.RestoreRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.RestoreResponse.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.InspectRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.InspectResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=criteria_dot_v2_dot_adapter__pb2.CloseSessionRequest.FromString,
                    response_serializer=criteria_dot_v2_dot_adapter__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criteria.v2.AdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('criteria.v2.AdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterService(object):
    """AdapterService is the out-of-process adapter contract for Criteria v2.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Info',
            criteria_dot_v2_dot_adapter__pb2.InfoRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/OpenSession',
            criteria_dot_v2_dot_adapter__pb2.OpenSessionRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criteria.v2.AdapterService/Execute',
            criteria_dot_v2_dot_adapter__pb2.ExecuteRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criteria.v2.AdapterService/Log',
            criteria_dot_v2_dot_adapter__pb2.LogRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.LogEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Permissions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/criteria.v2.AdapterService/Permissions',
            criteria_dot_v2_dot_adapter__pb2.PermissionEvent.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.PermissionDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Pause',
            criteria_dot_v2_dot_adapter__pb2.PauseRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Resume',
            criteria_dot_v2_dot_adapter__pb2.ResumeRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Snapshot',
            criteria_dot_v2_dot_adapter__pb2.SnapshotRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Restore',
            criteria_dot_v2_dot_adapter__pb2.RestoreRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/Inspect',
            criteria_dot_v2_dot_adapter__pb2.InspectRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v2.AdapterService/CloseSession',
            criteria_dot_v2_dot_adapter__pb2.CloseSessionRequest.SerializeToString,
            criteria_dot_v2_dot_adapter__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
