# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from criteria.v1 import adapter_plugin_pb2 as criteria_dot_v1_dot_adapter__plugin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in criteria/v1/adapter_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterPluginServiceStub(object):
    """AdapterPluginService defines the out-of-process adapter contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/criteria.v1.AdapterPluginService/Info',
                request_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.InfoRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/criteria.v1.AdapterPluginService/OpenSession',
                request_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/criteria.v1.AdapterPluginService/Execute',
                request_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.Permit = channel.unary_unary(
                '/criteria.v1.AdapterPluginService/Permit',
                request_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.PermitRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.PermitResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/criteria.v1.AdapterPluginService/CloseSession',
                request_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class AdapterPluginServiceServicer(object):
    """AdapterPluginService defines the out-of-process adapter contract.
    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Permit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterPluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.InfoRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.InfoResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteEvent.SerializeToString,
            ),
            'Permit': grpc.unary_unary_rpc_method_handler(
                    servicer.Permit,
                    request_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.PermitRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.PermitResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criteria.v1.AdapterPluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('criteria.v1.AdapterPluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterPluginService(object):
    """AdapterPluginService defines the out-of-process adapter contract.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.AdapterPluginService/Info',
            criteria_dot_v1_dot_adapter__plugin__pb2.InfoRequest.SerializeToString,
            criteria_dot_v1_dot_adapter__plugin__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.AdapterPluginService/OpenSession',
            criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionRequest.SerializeToString,
            criteria_dot_v1_dot_adapter__plugin__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criteria.v1.AdapterPluginService/Execute',
            criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteRequest.SerializeToString,
            criteria_dot_v1_dot_adapter__plugin__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Permit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.AdapterPluginService/Permit',
            criteria_dot_v1_dot_adapter__plugin__pb2.PermitRequest.SerializeToString,
            criteria_dot_v1_dot_adapter__plugin__pb2.PermitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.AdapterPluginService/CloseSession',
            criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionRequest.SerializeToString,
            criteria_dot_v1_dot_adapter__plugin__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
