# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from criteria.v1 import criteria_pb2 as criteria_dot_v1_dot_criteria__pb2
from criteria.v1 import events_pb2 as criteria_dot_v1_dot_events__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in criteria/v1/criteria_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CriteriaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/criteria.v1.CriteriaService/Register',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.RegisterRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/criteria.v1.CriteriaService/Heartbeat',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.CreateRun = channel.unary_unary(
                '/criteria.v1.CriteriaService/CreateRun',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.Run.FromString,
                _registered_method=True)
        self.ReattachRun = channel.unary_unary(
                '/criteria.v1.CriteriaService/ReattachRun',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.ReattachRunRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.ReattachRunResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/criteria.v1.CriteriaService/Resume',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.ResumeRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.SubmitEvents = channel.stream_stream(
                '/criteria.v1.CriteriaService/SubmitEvents',
                request_serializer=criteria_dot_v1_dot_events__pb2.Envelope.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.Ack.FromString,
                _registered_method=True)
        self.Control = channel.unary_stream(
                '/criteria.v1.CriteriaService/Control',
                request_serializer=criteria_dot_v1_dot_criteria__pb2.ControlSubscribeRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.ControlMessage.FromString,
                _registered_method=True)


class CriteriaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Register enrolls a Criteria agent with the orchestrator. Returns the assigned
        criteria id and an auth token the agent must present on all subsequent
        RPCs.

        Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
        an `X-Server-Bootstrap` header) before accepting Register. When no
        bootstrap mechanism is configured, implementations MUST return
        Unimplemented. This prevents open self-registration in production.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat advances the agent's `last_seen_at`. The orchestrator marks
        agents offline whose heartbeat is older than a configurable threshold.

        The authenticated caller's identity is the canonical criteria agent being
        updated. Implementations MUST ignore any request-supplied criteria_id and
        use the caller's authenticated identity instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRun(self, request, context):
        """CreateRun mints a new run owned by the authenticated caller. The
        orchestrator is the sole source of run ids.

        The run is always recorded under the authenticated caller's criteria ID.
        The request's `criteria_id` field is informational only. Implementations
        MUST ignore any request-supplied criteria_id and use the caller's
        authenticated identity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReattachRun(self, request, context):
        """ReattachRun lets a Criteria agent query the orchestrator about an in-flight run
        after a crash or restart. The orchestrator returns the current status,
        last active step, and whether the agent may resume execution.

        Implementations MUST reject the request with PERMISSION_DENIED if the
        authenticated caller does not own the target run's criteria agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Resume delivers a named signal (or an approval decision) to a paused run.

        Implementations MUST reject the request with PERMISSION_DENIED if the
        authenticated caller does not own the target run's criteria agent.

        This RPC is SDK contract surface: field names, payload semantics, and
        error-reason strings are stable for third-party orchestrators.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEvents(self, request_iterator, context):
        """SubmitEvents is a bidirectional stream. The client writes Envelopes and
        the server replies with an Ack per persisted envelope (run_id, seq,
        correlation_id). On reconnect the client may include `since_seq` in
        request metadata to request replay of events that were persisted but not
        yet acknowledged.

        Implementations MUST verify on every envelope that the authenticated caller
        owns the envelope's run_id. On the first violation the stream MUST be
        rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Control is a long-lived server-stream that the orchestrator uses to push
        commands to a connected Criteria agent (cancel a run, send a prompt to an
        agent, ...).

        The authenticated caller's identity determines the registry key for the
        Control subscription. Implementations MUST ignore any request-supplied
        criteria_id and use the caller's authenticated identity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CriteriaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.RegisterRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.HeartbeatRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.HeartbeatResponse.SerializeToString,
            ),
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.CreateRunRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.Run.SerializeToString,
            ),
            'ReattachRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ReattachRun,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.ReattachRunRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.ReattachRunResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.ResumeRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.ResumeResponse.SerializeToString,
            ),
            'SubmitEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.SubmitEvents,
                    request_deserializer=criteria_dot_v1_dot_events__pb2.Envelope.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.Ack.SerializeToString,
            ),
            'Control': grpc.unary_stream_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=criteria_dot_v1_dot_criteria__pb2.ControlSubscribeRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.ControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criteria.v1.CriteriaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('criteria.v1.CriteriaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CriteriaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.CriteriaService/Register',
            criteria_dot_v1_dot_criteria__pb2.RegisterRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.CriteriaService/Heartbeat',
            criteria_dot_v1_dot_criteria__pb2.HeartbeatRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.CriteriaService/CreateRun',
            criteria_dot_v1_dot_criteria__pb2.CreateRunRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReattachRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.CriteriaService/ReattachRun',
            criteria_dot_v1_dot_criteria__pb2.ReattachRunRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.ReattachRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.CriteriaService/Resume',
            criteria_dot_v1_dot_criteria__pb2.ResumeRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/criteria.v1.CriteriaService/SubmitEvents',
            criteria_dot_v1_dot_events__pb2.Envelope.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criteria.v1.CriteriaService/Control',
            criteria_dot_v1_dot_criteria__pb2.ControlSubscribeRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
