# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from criteria.v1 import criteria_pb2 as criteria_dot_v1_dot_criteria__pb2
from criteria.v1 import events_pb2 as criteria_dot_v1_dot_events__pb2
from criteria.v1 import server_pb2 as criteria_dot_v1_dot_server__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in criteria/v1/server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAgents = channel.unary_unary(
                '/criteria.v1.ServerService/ListAgents',
                request_serializer=criteria_dot_v1_dot_server__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/criteria.v1.ServerService/GetAgent',
                request_serializer=criteria_dot_v1_dot_server__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.Agent.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/criteria.v1.ServerService/ListRuns',
                request_serializer=criteria_dot_v1_dot_server__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/criteria.v1.ServerService/GetRun',
                request_serializer=criteria_dot_v1_dot_server__pb2.GetRunRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_criteria__pb2.Run.FromString,
                _registered_method=True)
        self.ListRunEvents = channel.unary_unary(
                '/criteria.v1.ServerService/ListRunEvents',
                request_serializer=criteria_dot_v1_dot_server__pb2.ListRunEventsRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.ListRunEventsResponse.FromString,
                _registered_method=True)
        self.WatchRun = channel.unary_stream(
                '/criteria.v1.ServerService/WatchRun',
                request_serializer=criteria_dot_v1_dot_server__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_events__pb2.Envelope.FromString,
                _registered_method=True)
        self.StopRun = channel.unary_unary(
                '/criteria.v1.ServerService/StopRun',
                request_serializer=criteria_dot_v1_dot_server__pb2.StopRunRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.StopRunResponse.FromString,
                _registered_method=True)
        self.SendPrompt = channel.unary_unary(
                '/criteria.v1.ServerService/SendPrompt',
                request_serializer=criteria_dot_v1_dot_server__pb2.SendPromptRequest.SerializeToString,
                response_deserializer=criteria_dot_v1_dot_server__pb2.SendPromptResponse.FromString,
                _registered_method=True)


class ServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunEvents(self, request, context):
        """ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRun(self, request, context):
        """WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
        persisted events (since `since_seq`) and then tails live events until the
        client disconnects or the run reaches a terminal state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRun(self, request, context):
        """StopRun cancels a run. If an agent is attached to the run via its
        Control stream, the orchestrator pushes a RunCancel to it. Returns
        FAILED_PRECONDITION if the agent is not connected.

        Implementations MUST reject the request with PERMISSION_DENIED if the
        authenticated caller does not own the target run's agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrompt(self, request, context):
        """SendPrompt — schema-only stub for Phase 2.3. UI clients can wire up
        against this method, but the server currently returns UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.ListAgentsRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.GetAgentRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.Agent.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.ListRunsRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.GetRunRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_criteria__pb2.Run.SerializeToString,
            ),
            'ListRunEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunEvents,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.ListRunEventsRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.ListRunEventsResponse.SerializeToString,
            ),
            'WatchRun': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRun,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.WatchRunRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_events__pb2.Envelope.SerializeToString,
            ),
            'StopRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRun,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.StopRunRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.StopRunResponse.SerializeToString,
            ),
            'SendPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrompt,
                    request_deserializer=criteria_dot_v1_dot_server__pb2.SendPromptRequest.FromString,
                    response_serializer=criteria_dot_v1_dot_server__pb2.SendPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criteria.v1.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('criteria.v1.ServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/ListAgents',
            criteria_dot_v1_dot_server__pb2.ListAgentsRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/GetAgent',
            criteria_dot_v1_dot_server__pb2.GetAgentRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/ListRuns',
            criteria_dot_v1_dot_server__pb2.ListRunsRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/GetRun',
            criteria_dot_v1_dot_server__pb2.GetRunRequest.SerializeToString,
            criteria_dot_v1_dot_criteria__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/ListRunEvents',
            criteria_dot_v1_dot_server__pb2.ListRunEventsRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.ListRunEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criteria.v1.ServerService/WatchRun',
            criteria_dot_v1_dot_server__pb2.WatchRunRequest.SerializeToString,
            criteria_dot_v1_dot_events__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/StopRun',
            criteria_dot_v1_dot_server__pb2.StopRunRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.StopRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criteria.v1.ServerService/SendPrompt',
            criteria_dot_v1_dot_server__pb2.SendPromptRequest.SerializeToString,
            criteria_dot_v1_dot_server__pb2.SendPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
